# Generated by Django 6.0.7 on 2026-07-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
