# Generated by Django 6.0.7 on 2026-08-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_status_quotation_quotationline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
